[package]
name = "req2struct"
version = "0.1.1"
authors = ["Andrew Yourtchenko <ayourtch@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
log = "0.4.0"
env_logger = "0.6.1"
